version: '3.7'

services:
  ubuntu:
    container_name: ubuntu
    build:
      args:
        - distro=ubuntu
        - tag=22.10
      context: .
    volumes:
      - .:/home/fakeuser/setup

  fedora:
    container_name: fedora
    build:
      args:
        - distro=fedora
        - tag=37
      context: .
    volumes:
      - .:/home/fakeuser/setup

  arch:
    container_name: arch
    build:
      args:
        - distro=archlinux
        - tag=latest
      context: .
    volumes:
      - .:/home/fakeuser/setup
