version: '3.7'

services:
  ubuntu:
    container_name: ubuntu
    build:
      args:
        - image=ubuntu:22.10
        - distro=Ubuntu
      context: .
    volumes:
      - ./src:/home/fakeuser

  fedora:
    container_name: fedora
    build:
      args:
        - image=fedora:37
        - distro=Fedora
      context: .
    volumes:
      - ./src:/home/fakeuser

  arch:
    container_name: arch
    build:
      args:
        - image=archlinux:latest
        - distro=Arch
      context: .
    volumes:
      - ./src:/home/fakeuser
