version: '3.7'

services:
  ubuntu:
    container_name: ubuntu
    build:
      args:
        - image=ubuntu:22.10
        - distro=kinetic
      context: .
    volumes:
      - ./src:/home/fakeuser/setup

  fedora:
    container_name: fedora
    build:
      args:
        - image=fedora:37
        - distro=ThirtySeven
      context: .
    volumes:
      - ./src:/home/fakeuser/setup

  arch:
    container_name: arch
    build:
      args:
        - image=archlinux:latest
        - distro=noetic
      context: .
    volumes:
      - ./src:/home/fakeuser/setup
